import './globals.css'
import '../../node_modules/react-grid-layout/css/styles.css'
import '../../node_modules//react-resizable/css/styles.css'
import '@fontsource/dejavu-sans/400.css'
import '@fontsource/dejavu-sans/400-italic.css'
import '@fontsource/dejavu-sans/700.css'
import '@fontsource/dejavu-sans/700-italic.css'
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from "@vercel/speed-insights/next"
import GetNav from './routing'
import { NextAuthProvider } from "./providers";
import { getSession } from "@/services/session"

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
   const session = await getSession();
   return (
      <html lang="en">
         <body className="font-sans">
            <GetNav
               session={session}
            />
            <NextAuthProvider>
               {children}
            </NextAuthProvider>
            <Analytics />
            <SpeedInsights />
         </body>
      </html>
   )
}