import './globals.css'
import { Inter } from 'next/font/google'
import GetNav from './routing'
import { NextAuthProvider } from "./providers";
import { getSession } from "@/services/session"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
   const session = await getSession();
   return (
      <html lang="en">
         <body className={inter.className}>
            <GetNav
               session={session}
            />
            <NextAuthProvider>
               {children}
            </NextAuthProvider>
         </body>
      </html>
   )
}