import './globals.css'
import '../../node_modules/react-grid-layout/css/styles.css'
import '../../node_modules//react-resizable/css/styles.css'
import { Inter } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from "@vercel/speed-insights/next"
import GetNav from './routing'
import { NextAuthProvider } from "./providers";
import { getSession } from "@/services/session"
import { scheduleSummary } from "@/services/summary";

const inter = Inter({
   subsets: ['latin'],
   variable: '--font-inter'
});

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
   const session = await getSession();
   scheduleSummary();
   return (
      <html lang="en">
         <body className={`${inter.variable} font-sans`}>
            <GetNav
               session={session}
            />
            <NextAuthProvider>
               {children}
            </NextAuthProvider>
            <Analytics />
            <SpeedInsights />
         </body>
      </html>
   )
}