import './globals.css'
import { Inter } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from "@vercel/speed-insights/next"
import GetNav from './routing'
import { NextAuthProvider } from "./providers";
import { getSession } from "@/services/session"
import { dir } from 'i18next'

const inter = Inter({ subsets: ['latin'] })
const languages = ['en', 'es', 'ca']

export async function generateStaticParams() {
   return languages.map((lng) => ({ lng }))
}

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default async function RootLayout({ children, params: {
   lng
} }: { children: React.ReactNode, params: any }) {
   const session = await getSession();
   return (
      <html lang={lng} dir={dir(lng)}>
         <body className={inter.className}>
            <GetNav
               session={session}
            />
            <NextAuthProvider>
               {children}
            </NextAuthProvider>
            <Analytics />
            <SpeedInsights />
         </body>
      </html>
   )
}